#!/usr/bin/python

import argparse
from bs4 import BeautifulSoup
import requests

parser = argparse.ArgumentParser()
parser.add_argument("word",help="word to define")
args = parser.parse_args()

source = requests.get('http://www.dictionary.com/browse/{}?s=t'.format(args.word)).text
soup = BeautifulSoup(source, 'lxml')
try:
    wordDef = soup.find('span', class_='css-9sn2pa e10vl5dg6').text
    print("{}".format(wordDef))
except Exception as e:
    print("definition not found\n")
